-- ============================================================
-- 09_inspect_all_tables.sql
-- Comprehensive inspection of all data in the Event Koi database
-- ============================================================
USE event_koi;
-- =====================================================
-- 1. CORE ENTITIES (The Foundation)
-- =====================================================
SELECT *
FROM Users;
SELECT *
FROM UserProfiles;
SELECT *
FROM Categories;
SELECT *
FROM Venues;
SELECT *
FROM Events;
-- =====================================================
-- 2. EVENTS & TICKETING
-- =====================================================
SELECT *
FROM TicketTypes;
SELECT *
FROM Bookings;
SELECT *
FROM Tickets;
SELECT *
FROM EventSchedule;
SELECT *
FROM EventWaitlist;
SELECT *
FROM EventCategories;
SELECT *
FROM EventTags;
-- =====================================================
-- 3. FINANCIALS & SPONSORSHIPS
-- =====================================================
SELECT *
FROM Payments;
SELECT *
FROM EventRevenue;
SELECT *
FROM Refunds;
SELECT *
FROM PlatformFees;
SELECT *
FROM Sponsors;
SELECT *
FROM SponsorshipPackages;
SELECT *
FROM EventSponsorships;
-- =====================================================
-- 4. SOCIAL INTERACTION
-- =====================================================
SELECT *
FROM EventPosts;
SELECT *
FROM PostLikes;
SELECT *
FROM PostComments;
SELECT *
FROM Friendships;
SELECT *
FROM UserFollowing;
SELECT *
FROM Messages;
SELECT *
FROM Notifications;
SELECT *
FROM EventReviews;
-- =====================================================
-- 5. ADMIN & SYSTEM
-- =====================================================
SELECT *
FROM AdminRoles;
SELECT *
FROM AdminUsers;
SELECT *
FROM AdminAuditLog;
SELECT *
FROM SystemLogs;
SELECT *
FROM RoleRequests;
SELECT *
FROM ReportedContent;
SELECT *
FROM UserModeration;
-- =====================================================
-- 6. ANALYTICS & PERSONALIZATION
-- =====================================================
SELECT *
FROM UserAnalytics;
SELECT *
FROM EventAnalytics;
SELECT *
FROM DailyMetrics;
SELECT *
FROM UserAchievements;
SELECT *
FROM UserPreferences;
SELECT *
FROM SearchHistory;
SELECT *
FROM UserRecommendations;
-- =====================================================
-- 7. RECOGNIZED VIEWS (Reporting)
-- =====================================================
SELECT *
FROM vw_eventsummary;
SELECT *
FROM vw_organizerperformance;
SELECT *
FROM vw_revenuereport;
SELECT *
FROM vw_userdashboard;